### ISSUE TITLE
SongControl not working in multiplayer

### ISSUE THREAD

**Issue by rakso20000** [Auros/SiraUtil#2]
SongControl is not working in multiplayer (at least for me)
I tried it in a private lobby with only one player and fpfc enabled in case that makes any difference.

**Comment by Auros** [comment]
Right now this is intentional. The main purpose for SongControl is pausing, leaving, and restarting the level (which obviously should be done in multi). I'm working on a trimmed down version which instead of pausing the level, will just summon the UI, and instead of ending the level, will just make you leave the lobby.

**Comment by Auros** [comment]
I kinda slept on this but I've internally set it up now. Coming to SiraUtil 2.1.0
